# Generated by Django 3.1.3 on 2020-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201107_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='file_f',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
