# Generated by Django 3.1.3 on 2020-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201107_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_f',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
